Activities/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #==========   VERB   ==========#
    path('verbs/', views.ListVerb.as_view(), name='verb_list'),
    path('verb/<int:pk>', views.DetailVerb.as_view(), name='verb_detail'),
    path('create_verb/', views.CreateVerb.as_view(), name='verb_create'),
    path('update_verb<int:pk>/',
         views.UpdateVerb.as_view(),
         name='verb_update'),
    path('delete_verb<int:pk>/',
         views.DeleteVerb.as_view(),
         name='verb_delete'),
    #==========   VERB   ==========#
    
    
    
    #==========   SENTENCE   ==========#
    path('sentences/', views.ListSentence.as_view(), name='sentence_list'),
    path('sentence/<int:pk>', views.DetailSentence.as_view(),
         name='sentence_detail'),
    path('create_sentence/', views.CreateSentence.as_view(),
         name='sentence_create'),
    path('update_sentence<int:pk>/',
         views.UpdateSentence.as_view(),
         name='sentence_update'),
    path('delete_sentence<int:pk>/',
         views.DeleteSentence.as_view(),
         name='sentence_delete'),
    #==========   SENTENCE   ==========#
    
    
    
    #==========   GROUP   ==========#
    path('groups/', views.ListGroup.as_view(), name='group_list'),
    path('group/<int:pk>', views.DetailGroup.as_view(),
         name='group_detail'),
    path('create_group/', views.CreateGroup.as_view(),
         name='group_create'),
    path('update_group<int:pk>/',
         views.UpdateGroup.as_view(),
         name='group_update'),
    path('delete_group<int:pk>/',
         views.DeleteGroup.as_view(),
         name='group_delete'),
    #==========   GROUP   ==========#

    
    
    #==========   PATTERN   ==========#
    path('patterns/', views.ListPattern.as_view(), name='pattern_list'),
    path('pattern/<int:pk>', views.DetailPattern.as_view(),
         name='pattern_detail'),
    path('create_pattern/', views.CreatePattern.as_view(),
         name='pattern_create'),
    path('update_pattern<int:pk>/',
         views.UpdatePattern.as_view(),
         name='pattern_update'),
    path('delete_pattern<int:pk>/',
         views.DeletePattern.as_view(),
         name='pattern_delete'),
    #==========   PATTERN   ==========#
    
    
    
    #==========   RESOURCE   ==========#
    path('resources/', views.ListResource.as_view(), name='resource_list'),
    path('resource/<int:pk>', views.DetailResource.as_view(),
         name='resource_detail'),
    path('create_resource/', views.CreateResource.as_view(),
         name='resource_create'),
    path('update_resource/<int:pk>',
         views.UpdateResource.as_view(),
         name='resource_update'),
    path('delete_resource/<int:pk>',
         views.DeleteResource.as_view(),
         name='resource_delete'),
    #==========   RESOURCE   ==========#
    
    
    
    #==========   ARTEFACT   ==========#
    path('artefacts/', views.ListArtefact.as_view(), name='artefact_list'),
    path('artefact/<int:pk>', views.DetailArtefact.as_view(),
         name='artefact_detail'),
    path('create_artefact/', views.CreateArtefact.as_view(),
         name='artefact_create'),
    path('update_artefact/<int:pk>',
         views.UpdateArtefact.as_view(),
         name='artefact_update'),
    path('delete_artefact/<int:pk>',
         views.DeleteArtefact.as_view(),
         name='artefact_delete'),
    #==========   ARTEFACT   ==========#
]

Core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home, name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(),
         name='search_results'),
]

GestaoDePraticasDiarias_v6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('', include('Users.urls')),
    path('', include('Activities.urls')),
    path('', include('processes.urls')),
]

Users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "Users"

urlpatterns = [
    path("utilizadores", views.utilizadores, name="utilizadores"),
    path("utilizadores/UserCreate", login_required(views.UserCreate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserCreate"),
    path("utilizadores/UserDelete/<int:pk>", login_required(views.UserDelete.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserDelete"),
    path("utilizadores/UserUpdate/<int:pk>", login_required(views.UserUpdate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserUpdate"),
    path("utilizadores/UserUpdateEmail/<int:pk>", login_required(views.UserUpdateEmail.as_view(success_url=('/')),login_url="/login"),  name="UserUpdateEmail"),
    path("utilizadores/UserChangePassword/<int:pk>", login_required(views.UserChangePassword.as_view(success_url=('/')),login_url="/login"),  name="UserUpdatePassword"),
    path("utilizadores/UserDetail/<int:pk>", login_required(views.UserDetail.as_view(),login_url="/login"), name="UserDetail"  ),
    path("empresas", views.empresas, name="empresas"),
    path("empresas/OrganizationCreate", login_required(views.OrganizationCreate.as_view(success_url=('/empresas')), login_url="/login"), name="empresas"),
    path("empresas/OrganizationDelete/<int:pk>", login_required(views.OrganizationDelete.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationDelete"),
    path("empresas/OrganizationUpdate/<int:pk>", login_required(views.OrganizationUpdate.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationUpdate"),
    path("empresas/OrganizationDetail/<int:pk>", login_required(views.OrganizationDetail.as_view(),login_url="/login"), name="OrganizationDetail"  ),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
]

Activities/models.py
from django.db import models

# Create your models here.


class Tags(models.Model):
    name = models.IntegerField(db_column='Name', blank=True, null=True)
    id = models.AutoField(db_column='ID', primary_key=True)

    class Meta:
        managed = True
        db_table = 'Tags'


class Pattern(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID')
    patternname = models.CharField(db_column='PatternName', max_length=255, verbose_name='Padrão')
    description = models.TextField(db_column='Description')
    data_creation = models.DateField(db_column='Data Creation', null=True)
    groups = models.ManyToManyField('Group')

    class Meta:
        managed = True
        db_table = 'Pattern'
    def __str__(self):
        return self.patternname
    def list_groups(self):
        return ", ".join([groups.groupname for groups in self.groups.all()])


class Group(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, null=True, db_column='UserID')
    groupname = models.CharField(db_column='GroupName', unique=True, max_length=255, verbose_name='Agrupamento')
    creationdate = models.DateField(db_column='CreationDate', blank=True, null=True)
    name = models.CharField(db_column='Name', max_length=255)
    description = models.TextField(db_column='Description')
    sentences = models.ManyToManyField('Sentence')

    class Meta:
        managed = True
        db_table = 'Group'
    def __str__(self):
        return self.groupname
    def list_sentences(self):
        return ", ".join([sentences.sentencename for sentences in self.sentences.all()])


class Sentence(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID')
    sentencename = models.CharField(db_column='SentenceName', max_length=255, verbose_name="Frase")
    datecreated = models.DateField(db_column='DateCreated', null=True)
    subject = models.CharField(db_column='Subject', max_length=255, verbose_name="Sujeito")
    receiver = models.CharField(db_column='Receiver', max_length=255, blank=True, null=False, verbose_name="Recetor")
    datarealizado = models.DateField(db_column='DataRealizado',blank=True, null=True)
    verbid = models.ForeignKey('Verb', models.DO_NOTHING, db_column='VerbID', verbose_name="Verbo", blank=True, null=True)
    resourceid = models.ForeignKey('Resource', models.SET_NULL, db_column='ResourceID', verbose_name="Recurso", null=True, blank=True)
    artefactid = models.ForeignKey('Artefact', models.SET_NULL, db_column='ArtefactID', verbose_name="Artefacto", null=True, blank=True)

    verb_sug = models.CharField(db_column='VerbSug', max_length=255, verbose_name="Verbo Sugerido", blank=True)

    resource_sug = models.CharField(db_column='ResourceSug', max_length=255, verbose_name="Recurso Sugerido", blank=True)

    art_sug = models.CharField(db_column='ArtefactSug', max_length=255, verbose_name="Artefacto Sugerido", blank=True)

    class Meta:
        managed = True
        db_table = 'Sentence'
    def __str__(self):
        return self.sentencename


class Verb(models.Model):
    verb_type_choices = (('Produtivo','Produtivo'), ('Comunicativo','Comunicativo'))
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID', blank=True, null=True)
    datecreated = models.DateField(db_column='DateCreated', blank=True, null=True)
    verbname = models.CharField(db_column='VerbName', unique=True, max_length=255, verbose_name='Verbo')
    verbtype = models.CharField(db_column='VerbType', max_length=255, choices=verb_type_choices, verbose_name='Tipo')

    class Meta:
        managed = True
        db_table = 'Verb'
    def __str__(self):
        return self.verbname
        
        
        
class Resource(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID', blank=True, null=True)
    resourcename = models.CharField(db_column='ResourceName', unique=True, max_length=255, verbose_name='Recurso')
    datecreated = models.DateField(db_column='DateCreated')

    class Meta:
        managed = True
        db_table = 'Resource'
    def __str__(self):
        return self.resourcename
 
 
class Artefact(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    userid = models.ForeignKey('Users.User', models.DO_NOTHING, db_column='UserID', blank=True, null=True)
    artefactname = models.CharField(db_column='ArtefactName', unique=True, max_length=255, verbose_name='Artefacto')
    datecreated = models.DateField(db_column='DateCreated')

    class Meta:
        managed = True
        db_table = 'Artefacto'
    def __str__(self):
        return self.artefactname
       

Users/models.py
import django
from django.db import models
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import AbstractUser, Group

# Create your models here.
class Organization(models.Model):
    name = models.CharField(max_length=200, unique=True, blank=False)
    location = models.CharField(max_length=200, blank=False)
    def __str__(self):
        return self.name



class User(AbstractUser):
    id = models.AutoField(db_column='ID',primary_key=True)
    username = models.CharField(db_column='UserName',
                                max_length=255,
                                unique=True)
    useremail = models.CharField(db_column='UserEmail',
                                 max_length=255)
    password = models.CharField(db_column='Password',
                                max_length=255,
                                blank=True, null=True)

    organization = models.ForeignKey(Organization, null=True,blank=True, on_delete=models.SET_NULL)




    class Meta:
        managed = True
        db_table = 'User'
        permissions = (
            ("test_GProc", "Teste de permissao geral Gestor de Processos"),
            ("test_Analist", "Teste de permissao geral Analista"),
            ("test_Func", "Teste de permissao geral Funcionário"),
            ("test_Admin", "Teste de permissao geral Administrador"),)

Activities/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from .models import Sentence


class SentenceForm(forms.ModelForm):


    def clean(self):
        super(SentenceForm, self).clean()
        if bool(self.cleaned_data['verbid']) == bool(
                self.cleaned_data['verb_sug']):
            raise ValidationError("Please, fill the first or second field")

    class Meta:
        model = Sentence
        fields = ['sentencename', 'subject', 'verb_sug', 'verbid',
                  'receiver', 'resource_sug', 'resourceid',
                  'art_sug', 'artefactid', 'datarealizado']

Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from tinymce.widgets import TinyMCE
from django.db import models
from .models import   User, Organization
from django.forms import ModelForm

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    group = forms.ModelChoiceField(queryset=Group.objects.all())
    organization = forms.ModelChoiceField(queryset=Organization.objects.all())
    class Meta:
        model = User
        fields = ("username", "email", "group", "organization", "password1", "password2",)
        

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        profile= self.cleaned_data.get('group')
        group = profile
        organization = self.cleaned_data['organization']
        if commit:
            user.save()
            user.groups.set(profile)
        return user

templates/tables/activity.html
<table class="table table-hover header-fixed my-5">
      <thead>
        <tr class="d-flex">
          <th class="col-9">Minhas atividades</th>
          <th class="col-3 text-right">
            <a class="ropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span>Mais recente</span><i class="material-icons">arrow_drop_down</i></a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Mais antigo</a>
              <a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_downward</i></a>
              <a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_upward</i></a>
            </div>
          </th>
        </tr>
      </thead>
      <tbody style="max-height: 60vh;">
        <tr class="d-flex">
          <td class="col-9"><b><a href= '{% url "group_create" %}' class="novo"><i class="material-icons">add</i> Nova atividade</a></b></td>
          <td class="col-3 text-right"></td>
        </tr>
        {% for atividade in object_list %}
        <tr class="d-flex">
          <td class="d-block col-8">{{ atividade.activityname }}</td>
          <td class="d-block col-4 text-right">{{ atividade.creationdate }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

templates/tables/artefact.html
<table class="table table-hover header-fixed my-5">
    <thead>
        <tr class="d-flex">
            <td class="col-12">
                <h2 class="d-inline mr-4 mt-4">Arefactos</h2>
                {% if request.path == '/artefacts/' %}<form class="d-inline form-inline mt-3" method="GET">
                    <input type="search" class="form-control" name="search" placeholder="Procurar...">
                    <button class="btn text-white">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                {% endif %}
            </td>
        </tr>
    </thead>
    <tbody style="max-height: 55vh;">
            {% if perms.Activities.add_artefact %}
        <tr class="d-flex">
            <td class="col-9"><a data-toggle="modal" onclick='newModal("{% url "artefact_create" %}", "Novo artefacto", "#modal", "")' href=""><h3 style="color:#058096;"><i class="material-icons mr-2">add</i> Novo Artefacto</h3></a></td>
            <td class="col-3 text-right"></td>
        </tr>
        {% endif %}
        {% for artefacto in object_list %}
        <tr class="d-flex">
            <td class="d-block col-5"> <a data-toggle="modal" onclick='newModal("{% url "artefact_detail" artefacto.id %}", "Detalhes do Artefacto", "#detailModal", "")' href="">{{ artefacto.artefactname }}</a></td>
            <td class="d-block col-3 text-right">{{ artefacto.userid }}</td>
            <td class="d-block col-3 text-right">{{ artefacto.datecreated }}</td>
            <td class="d-block col-1 text-right">
            {% if perms.Users.test_Analist %}
                <a data-toggle="modal" onclick='newModal("{% url "artefact_update" artefacto.id %}", "Editar Artefacto", "#modal", "")' href=''><i class="material-icons">create</i></a>
                <a data-toggle="modal" onclick='newModal("{% url "artefact_delete" artefacto.id %}", "Eliminar Artefacto", "#deleteModal", "", "#del")' href=''><i class="material-icons text-danger">clear</i></a>
            {% endif %}
           </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

  

templates/tables/group.html
<table class="table table-hover header-fixed my-5">
    <thead>
        <tr class="d-flex">
            <td class="col-12">
                <h2 class="d-inline mr-4 mt-4">Agrupamentos</h2>
                {% if request.path == '/groups/' %}<form class="d-inline form-inline mt-3" method="GET">
                    <input type="search" class="form-control" name="search" placeholder="Procurar...">
                    <button class="btn text-white">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                {% endif %}
            </td>
        </tr>
    </thead>
    <tbody style="max-height: 55vh;">
        {% if perms.Activities.add_group %}
            <tr class="d-flex">
               <td class="col-9"><a href="{% url 'sentence_list' %}"><h3 style="color:#058096;"><i class="material-icons mr-2">add</i> Novo Agrupamento</h3></a></td>
            </tr>
        {% endif %}
        {% for agrupamento in object_list %}
        <tr class="d-flex markerDiv">
            {% if perms.Users.test_Analist and request.path == '/groups/' %}<td class="d-block col-1"><input onclick="this.checked=!this.checked;" type="checkbox" name="markerType" id="{{ agrupamento.id }}" class="mt-1"/></td>{% endif %}
            <td class="d-block {% if perms.Users.test_Analist and request.path == '/groups/' %}col-3{% else %}col-4{% endif %}"><a id="noCheck" data-toggle="modal" onclick='newModal("{% url "group_detail" agrupamento.id %}", "Detalhes do Agrupamento", "#detailModal", "modal-lg")' href="">{{ agrupamento.groupname }}</a></td>
            <td class="d-block col-5"><a id="noCheck" data-toggle="modal" onclick='newModal("{% url "group_detail" agrupamento.id %}", "Detalhes do Agrupamento", "#detailModal", "modal-lg")' href="">{{ agrupamento.description }}</a></td>
            <td class="d-block col-2 text-right">{{ agrupamento.creationdate }}</td>
            <td class="d-block col-1 text-right">
            {% if perms.Users.test_Analist %}   
                <a data-toggle="modal" onclick='newModal("{% url "group_update" agrupamento.id %}", "Editar Agrupamento", "#modal", "")' href=''><i class="material-icons" id="noCheck">create</i></a>
                <a data-toggle="modal" onclick='newModal("{% url "group_delete" agrupamento.id %}", "Eliminar Agrupamento", "#deleteModal", "", "#del")' href=''><i class="material-icons text-danger" id="noCheck">clear</i></a>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="newChecked" style="display:none">
    <button type="button" href="#" class="btn float-right text-white" data-toggle="modal" onclick='newModal("{% url "pattern_create" %}", "Novo Padrão", "#modal", "modal-lg")'><i class="fas fa-link"></i> Associar agrupamentos a padrão</button>
</div>

templates/tables/resource.html
<table class="table table-hover header-fixed my-5">
    <thead>
        <tr class="d-flex">
            <td class="col-12">
                <h2 class="d-inline mr-4 mt-4">Recursos</h2>
                {% if request.path == '/resources/' %}<form class="d-inline form-inline mt-3" method="GET">
                    <input type="search" class="form-control" name="search" placeholder="Procurar...">
                    <button class="btn text-white">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                {% endif %}
            </td>
        </tr>
    </thead>
    <tbody style="max-height: 60vh;">
            {% if perms.Activities.add_resource %}
        <tr class="d-flex">
            <td class="col-9"><a data-toggle="modal" onclick='newModal("{% url "resource_create" %}", "Novo Recurso", "#modal", "")' href=""><h3 style="color:#058096;"><i class="material-icons mr-2">add</i> Novo Recurso</h3></a></td>
            <td class="col-3 text-right"></td>
        </tr>{% endif %}
        {% for recurso in object_list %}
        <tr class="d-flex">
            <td class="d-block col-5"> <a data-toggle="modal" onclick='newModal("{% url "resource_detail" recurso.id %}", "Detalhes do Recurso", "#detailModal", "")' href="">{{ recurso.resourcename }}</a></td>
            <td class="d-block col-3 text-right">{{ recurso.userid }}</td>
            <td class="d-block col-3 text-right">{{ recurso.datecreated }}</td>
            <td class="d-block col-1 text-right">
            {% if perms.Users.test_Analist %}
                <a data-toggle="modal" onclick='newModal("{% url "resource_update" recurso.id %}", "Editar Recurso", "#modal", "")' href=""><i class="material-icons">create</i></a>
                <a data-toggle="modal" onclick='newModal("{% url "resource_delete" recurso.id %}", "Eliminar Recurso", "#deleteModal", "", "#del")' href=''><i class="material-icons text-danger">clear</i></a>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

  

templates/tables/sentence.html
<table class="table table-hover header-fixed my-5">
    <thead>
        <tr class="d-flex">
            <td class="col-12">
                <h2 class="d-inline mr-4 mt-4">Frases</h2>
                {% if request.path == '/sentences/' %}<form class="d-inline form-inline mt-3" method="GET">
                    <input type="search" class="form-control" name="search" placeholder="Procurar...">
                    <button class="btn text-white">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                {% endif %}
            </td>
        </tr>
        {% if perms.Activities.add_sentence %}
            <tr class="d-flex" style="border-bottom:0px;">
                <td class="col-12"><a data-toggle="modal" onclick='newModal("{% url "sentence_create" %}", "Nova Frase", "#modal","modal-lg")' href=""><h3 style="color:#058096;"><i class="material-icons mr-2">add</i> Nova frase</h3></a></td>
            </tr>
        {% endif %}
    </thead>
    <tbody style="max-height: 55vh;">
            {% for frase in object_list %}
                <tr class="d-flex markerDiv">
                    {% if perms.Activities.add_group and request.path == '/sentences/' %}<td class="d-block col-1"><input onclick="this.checked=!this.checked;" type="checkbox" name="markerType" id="{{ frase.id }}" class="mt-1"/></td>{% endif %}
                    <td class="d-block col-2"><a data-toggle="modal" onclick='newModal("{% url "sentence_detail" frase.id %}", "Detalhes da Frase", "#detailModal", "modal-lg");' id="noCheck" href="" >{{ frase.datarealizado }}</a></td>
                    <td class="d-block col-2"><a data-toggle="modal" onclick='newModal("{% url "sentence_detail" frase.id %}", "Detalhes da Frase", "#detailModal", "modal-lg");' id="noCheck" href="" >{{ frase.subject }}</a></td>
                    <td class="d-block col-2"><a data-toggle="modal" onclick='newModal("{% url "sentence_detail" frase.id %}", "Detalhes da Frase", "#detailModal", "modal-lg");' id="noCheck" href="" >            {% if frase.verbid %}
            {{frase.verbid}}
            {% else %}
            {{frase.verb_sug}} {% if perms.Users.test_Analist %} <a data-toggle="modal" onclick='newModal("{% url "verb_create" %}", "Novo Verbo", "#modal", "")' href=""><i class="material-icons mr-2">add</i></a>{% endif %}
            {% endif %}
</a></td>
                    <td class="d-block{% if perms.Users.test_Analist and request.path == '/sentences/' %} col-2{% else %} col-3{% endif %}"><a data-toggle="modal" onclick='newModal("{% url "sentence_detail" frase.id %}", "Detalhes da Frase", "#detailModal", "modal-lg");' id="noCheck" href="" >{{ frase.receiver }}</a></td>
                    <td class="d-block col-2 text-right">{{ frase.datecreated }}</td>
                    <td class="d-block col-1 text-right">
                    {% if perms.Users.test_Func %}
                        <a data-toggle="modal" onclick='newModal("{% url "sentence_update" frase.id %}", "Editar Frase", "#modal", "modal-lg")' href=''><i class="material-icons" id="noCheck">create</i></a>
                        <a data-toggle="modal" onclick='newModal("{% url "sentence_delete" frase.id %}", "Eliminar Frase", "#deleteModal", "", "#del")' href=''><i class="material-icons text-danger" id="noCheck">clear</i></a>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
    </tbody>
</table>
<div class="newChecked" style="display:none">
    <button type="button" href="#" class="btn float-right text-white" data-toggle="modal" onclick='newModal("{% url "group_create" %}", "Novo Agrupamento", "#modal", "modal-lg")'><i class="fas fa-link"></i> Associar frases a agrupamento</button>
</div>


<!-- onclick='newModal("{% url "group_create" %}", "Novo Agrupamento", "#modal", "")' -->

templates/tables/verb.html
<table class="table table-hover header-fixed my-5">
    <thead>
      <tr class="d-flex">
            <td class="col-12">
                <h2 class="d-inline mr-4 mt-4">Verbos</h2>
                {% if request.path == '/verbs/' %}<form class="d-inline form-inline mt-3" method="GET">
                    <input type="search" class="form-control" name="search" placeholder="Procurar...">
                    <button class="btn text-white">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
                {% endif %}
            </td>
        </tr>
    </thead>
    <tbody style="max-height: 60vh;">
              {% if perms.Activities.add_verb %}
        <tr class="d-flex">
            <td class="col-9"><a data-toggle="modal" onclick='newModal("{% url "verb_create" %}", "Novo Verbo", "#modal", "")' href=""><h3 style="color:#058096;"><i class="material-icons mr-2">add</i> Novo Verbo</h3></a></td>
            <td class="col-3 text-right"></td>
        </tr>
        {% endif %}
        {% for verbo in object_list %}
        <tr class="d-flex">
            <td class="d-block col-3"><a data-toggle="modal" onclick='newModal("{% url "verb_detail" verbo.id %}", "Detalhes do Verbo", "#detailModal", "")' href="">{{ verbo.verbname }}</a></td>
            <td class="d-block col-4">{{ verbo.verbtype }}</td>
            <td class="d-block col-2">{{ verbo.userid }}</td>
            <td class="d-block col-2 text-right">{{ verbo.datecreated }}</td>
            <td class="d-block col-1 text-right">
            {% if perms.Users.test_Analist %}
                <a data-toggle="modal" onclick='newModal("{% url "verb_update" verbo.id %}", "Editar Verbo", "#modal", "")' href=""><i class="material-icons">create</i></a>
                <a data-toggle="modal" onclick='newModal("{% url "verb_delete" verbo.id %}", "Eliminar Verbo", "#deleteModalVerb", "", "#delverb")' href=''><i class="material-icons text-danger">clear</i></a>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>