Core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home, name='home'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(),
         name='search_results'),
]

GestaoDePraticasDiarias_v6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.urls')),
    path('', include('Users.urls')),
    path('', include('Activities.urls')),
    path('', include('processes.urls')),
]

Users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "Users"

urlpatterns = [
    path("utilizadores", views.utilizadores, name="utilizadores"),
    path("utilizadores/UserCreate", login_required(views.UserCreate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserCreate"),
    path("utilizadores/UserDelete/<int:pk>", login_required(views.UserDelete.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserDelete"),
    path("utilizadores/UserUpdate/<int:pk>", login_required(views.UserUpdate.as_view(success_url=('/utilizadores')),login_url="/login"),  name="UserUpdate"),
    path("utilizadores/UserUpdateEmail/<int:pk>", login_required(views.UserUpdateEmail.as_view(success_url=('/')),login_url="/login"),  name="UserUpdateEmail"),
    path("utilizadores/UserChangePassword/<int:pk>", login_required(views.UserChangePassword.as_view(success_url=('/')),login_url="/login"),  name="UserUpdatePassword"),
    path("utilizadores/UserDetail/<int:pk>", login_required(views.UserDetail.as_view(),login_url="/login"), name="UserDetail"  ),
    path("empresas", views.empresas, name="empresas"),
    path("empresas/OrganizationCreate", login_required(views.OrganizationCreate.as_view(success_url=('/empresas')), login_url="/login"), name="empresas"),
    path("empresas/OrganizationDelete/<int:pk>", login_required(views.OrganizationDelete.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationDelete"),
    path("empresas/OrganizationUpdate/<int:pk>", login_required(views.OrganizationUpdate.as_view(success_url=('/empresas')),login_url="/login"),  name="OrganizationUpdate"),
    path("empresas/OrganizationDetail/<int:pk>", login_required(views.OrganizationDetail.as_view(),login_url="/login"), name="OrganizationDetail"  ),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
]

processes/urls.py
from django.urls import path
from . import views 
from django.contrib.auth.decorators import login_required

app_name = "processes"

urlpatterns = [
    path("processos", views.processos, name="processos"),
    path("processos/ProcessCreate", login_required(views.ProcessCreate.as_view(success_url=('/processos')),login_url="/login"), name="ProcessCreate"),
    path("processos/ProcessUpdate/<int:pk>", login_required(views.ProcessUpdate.as_view(success_url=('/processos')),login_url="/login"), name="ProcessUpdate"),
    path("processos/ProcessDelete/<int:pk>", login_required(views.ProcessDelete.as_view(success_url=('/processos')),login_url="/login"), name="ProcessDelete"),
    path("processos/ProcessDetail/<int:pk>", login_required(views.ProcessDetail.as_view(),login_url="/login"), name="ProcessDetail"),
    path("actividades", views.actividades, name="actividades"),
    path("actividades/ActivityCreate", login_required(views.ActivityCreate.as_view(success_url=('/actividades')),login_url="/login"), name="ActivityCreate"),
    path("actividades/ActivityDetail/<int:pk>", login_required(views.ActivityDetail.as_view(), login_url="/login"), name="ActivityDetail"),
    path("actividades/ActivityUpdate/<int:pk>", login_required(views.ActivityUpdate.as_view(success_url=('/actividades')),login_url="/login") , name="ActivityUpdate"),
    path("actividades/ActivityDelete/<int:pk>", login_required(views.ActivityDelete.as_view(success_url=('/actividades')),login_url="/login"), name="ActivityDelete"),
    path("actividades/ActivitySwap/<int:pk>/<int:fk>", login_required(views.ActivitySwap.as_view(success_url=('/actividades/AssociateReferer')),login_url="/login"), name="ActivitySwap"),
    path("actividades/AssociateReferer", views.AssociateReferer, name="AssociateReferer"),
    path("actividades/ActivityDessociate/<int:pk>", views.removeActivityFromProcess, name="ActivityDessociate"),
    path("actividades/PatternDessociate/<int:pk>/<int:fk>", views.removePatternFromActivity, name="PatternDessociate"),
    path("actividades/PatternAssociate/<int:pk>/<int:fk>", views.addPatternToActivity, name="PatternAssociate"),
    path("produtos", views.produtos, name="produtos"),
    path("produtos/ProductCreate", login_required(views.ProductCreate.as_view(success_url=('/produtos')),login_url="/login"), name="ProductCreate"),
    path("produtos/ProductDetail/<int:pk>", login_required(views.ProductDetail.as_view(),login_url="/login"), name="ProductDetail"),
    path("produtos/ProductUpdate/<int:pk>", login_required(views.ProductUpdate.as_view(success_url=('/produtos')),login_url="/login"), name="ProductUpdate"),
    path("produtos/ProductDelete/<int:pk>", login_required(views.ProductDelete.as_view(success_url=('/produtos')),login_url="/login"), name="ProductDelete"),
    path("produtos/ProductDessociate/<int:pk>/<int:fk>", views.removeActivityFromProduct, name="ProductDessociate"),
    path("produtos/ProductAssociate/<int:pk>/<int:fk>", views.addActivityToProduct, name="ProductAssociate"),
    path("papeis", views.papeis, name="papeis"),
    path("papeis/RoleCreate", login_required(views.RoleCreate.as_view(success_url=('/papeis')),login_url="/login"), name="RoleCreate"),
    path("papeis/RoleDetail/<int:pk>", login_required(views.RoleDetail.as_view(),login_url="/login"), name="RoleDetail"),
    path("papeis/RoleUpdate/<int:pk>", login_required(views.RoleUpdate.as_view(success_url=('/papeis')),login_url="/login"), name="RoleUpdate"),
    path("papeis/RoleDelete/<int:pk>", login_required(views.RoleDelete.as_view(success_url=('/papeis')),login_url="/login"), name="RoleDelete"),
    path("actividades/RoleDessociate/<int:pk>/<int:fk>", views.removeRoleFromActivity, name="RoleDessociate"),
    path("actividades/RoleAssociate/<int:pk>/<int:fk>", views.addRoleToActivity, name="RoleAssociate"),
    path('actividades/SeeProcess/<int:pk>/', views.ViewProcess.as_view(), name='ViewProcess'),
    path('actividades/SeePattern/<int:pk>/', views.ViewPattern.as_view(), name='ViewPattern'),
    path('actividades/SeeProduct/<int:pk>/', views.ViewProduct.as_view(), name='ViewProduct'),
    path('actividades/SeeRole/<int:pk>/', views.ViewRole.as_view(), name='ViewRole'),
    path('actividades/SeeActivity/<int:pk>/', views.ViewActivity.as_view(), name='ViewActivity'),
]

Processes/views.py
from django.shortcuts import render

# Create your views here.

processes/views.py
from django.shortcuts import render, redirect 
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from .models import  Process, Activity, Role, Product
from Users.models import User, Organization
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from Users.forms import NewUserForm
from Activities.models import Pattern
from Activities.views import AjaxableResponseMixin
from .forms import  SwapActivityForm
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView
from django import forms




@login_required(login_url='/login')
def processos(request):
	return render(request=request,
				  template_name="processes/processos.html",
				   context={"procs": Process.objects.filter(user__organization=request.user.organization), "acts": Activity.objects.all()})


@login_required(login_url='/login')
def actividades(request):
	return render(request=request,
				  template_name="processes/actividades.html",
				   context={"acts": Activity.objects.all().exclude(original__isnull=False), "proc_acts": Activity.objects.filter(process__user=request.user)})

@login_required(login_url='/login')
def removeActivityFromProcess(request, **kwargs):
	this_act = Activity.objects.filter(pk=kwargs['pk'])[0]
	messages.warning(request,f"Actividade \""+ this_act.activity_name+ f"\" apagada do sistema")
	this_act.delete()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))#previous URL


class ActivityCreate(CreateView):
	model = Activity
	fields = ['activity_name', 'description', 'pattern', 'role'] 
	template_name = "processes/forms/activity_form.html"
	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()
		form = super(ActivityCreate, self).get_form(form_class)
		#form.fields['user'].widget
		form.fields['pattern'] = forms.ModelMultipleChoiceField(queryset=Pattern.objects.all() ,widget=forms.CheckboxSelectMultiple(), required=False)
		form.fields['role'] = forms.ModelMultipleChoiceField(queryset=Role.objects.all() ,widget=forms.CheckboxSelectMultiple(),required=False)
		form.fields['activity_name'].label = "Nome da actividade"
		form.fields['description'].label = "Descrição"
		form.fields['pattern'].label = "Padrões"
		form.fields['role'].label = "Papéis"
		return form	

	def form_valid(self, form):
		messages.info(self.request, f"Actividade " +  " \""+ form.cleaned_data['activity_name'] + f"\" inserida no sistema")
		return super(ActivityCreate, self).form_valid(form)

class ActivityDetail(DetailView):
	model = Activity
	template_name = "processes/forms/activity_detail.html"
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		act_id = self.object.id
		context['pid'] = self.kwargs['pk']
		our_products = Product.objects.all().filter(activity__id=act_id)
		this_act = Activity.objects.all().filter(id=act_id)[0]
		our_roles = this_act.role.all()
		our_patterns = this_act.pattern.all()
		context['act_products'] = our_products
		context['non_products'] = Product.objects.all().exclude(id__in=our_products)
		context['patterns'] = our_patterns
		context['non_patterns'] = Pattern.objects.all().exclude(id__in=our_patterns)
		context['roles'] = our_roles
		context['non_roles'] = Role.objects.all().exclude(id__in=our_roles)
		context['procs'] = Process.objects.all()
		return context

class ActivityUpdate(UpdateView):
	model = Activity
	fields = ['activity_name', 'description', 'pattern', 'role'] 
	template_name = "processes/forms/activity_update_form.html"
	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()
		form = super(ActivityUpdate, self).get_form(form_class)
		#form.fields['user'].widget
		form.fields['role'] = forms.ModelMultipleChoiceField(queryset=Role.objects.all() ,widget=forms.CheckboxSelectMultiple(), required=False)
		form.fields['pattern'] = forms.ModelMultipleChoiceField(queryset=Pattern.objects.all() ,widget=forms.CheckboxSelectMultiple(), required=False)
		form.fields['activity_name'].label = "Nome da actividade"
		form.fields['description'].label = "Descrição"
		form.fields['pattern'].label = "Padrões"
		form.fields['role'].label = "Papéis"
		return form		

	def form_valid(self, form):
		messages.info(self.request, f"Actividade " +  " \""+ form.cleaned_data['activity_name'] + f"\" alterada com sucesso")
		return super(ActivityUpdate, self).form_valid(form)

class ActivityDelete(DeleteView):
	model = Activity
	template_name = "processes/forms/activity_confirm_delete.html"
	def get_context_data(self, **kwargs):
		context = super(ActivityDelete, self).get_context_data(**kwargs)
		this_acts = Activity.objects.filter(original=self.kwargs['pk'])
		context['act_procs'] = this_acts
		return context

	def delete(self, request, *args, **kwargs):
		messages.warning(self.request,f"Actividade " +  " \""+ Activity.objects.filter(id=self.kwargs['pk'])[0].activity_name+ f"\" apagada do sistema")
		return super(ActivityDelete, self).delete(request, *args, **kwargs)

class ActivitySwap(CreateView):
	model = Activity
	sucess_url = "/actividades"
	template_name = "processes/forms/activity_update_form.html"
	fields = ['activity_name', 'description', 'role', 'pattern', 'process', 'original']
	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()
		form = super(ActivitySwap, self).get_form(form_class)
		this_act = Activity.objects.filter(pk =self.kwargs['pk'])[0]
		this_proc = Process.objects.filter(pk =self.kwargs['fk'])[0]
		form.fields['activity_name'].widget = forms.TextInput(attrs={'value': this_act.activity_name})
		form.fields['description'].widget = forms.TextInput(attrs={'value': this_act.description})
		all_roles = Role.objects.all()
		original_choice = Activity.objects.filter(pk =self.kwargs['pk'])
		form.fields['pattern'] = forms.ModelMultipleChoiceField(queryset=Pattern.objects.all(), widget=forms.CheckboxSelectMultiple(), required=False)
		form.fields['role'] = forms.ModelMultipleChoiceField(queryset=all_roles, widget=forms.CheckboxSelectMultiple(), required=False)
		form.fields['original'] = forms.ModelChoiceField(queryset=original_choice, widget=forms.RadioSelect())
		form.fields['original'].empty_label = None
		form.fields['process'].empty_label = None
		roles = Role.objects.filter(pk__in = this_act.role.all())
		patterns = Pattern.objects.filter(pk__in = this_act.pattern.all())
		form.initial['role'] = roles
		form.initial['process'] = this_proc
		form.initial['pattern'] = patterns
		form.initial['original'] = this_act.id
		return form

	def form_valid(self, form):
		messages.info(self.request, f"Actividade " +  " \""+ form.cleaned_data['activity_name'] + f"\" associada ao processo \" " + form.cleaned_data['process'].process_name +" \"")
		return super(ActivitySwap, self).form_valid(form)


@login_required(login_url='/login')
def AssociateReferer(request, **kwargs):
	split = request.META.get('HTTP_REFERER').split("/")
	return HttpResponseRedirect("/processos/ProcessDetail/"+split[-1])

@login_required(login_url='/login')
def removePatternFromActivity(request, **kwargs):
	this_act = Activity.objects.filter(pk=kwargs['pk'])[0]
	this_pattern = Pattern.objects.filter(pk=kwargs['fk'])[0]
	this_act.pattern.remove(this_pattern)
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))#previous URL

@login_required(login_url='/login')
def addPatternToActivity(request, **kwargs):
	this_act = Activity.objects.filter(pk=kwargs['pk'])[0]
	this_pattern = Pattern.objects.filter(pk=kwargs['fk'])[0]
	this_act.pattern.add(this_pattern)
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class ProcessCreate(CreateView):
	model = Process
	fields = ['process_name', 'user' , 'description']
	template_name = "processes/forms/process_form.html"
	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()
		form = super(ProcessCreate, self).get_form(form_class)
		form.fields['user'].widget = forms.HiddenInput()
		form.initial['user'] = self.request.user
		form.fields['process_name'].label = "Nome do Processo"
		form.fields['description'].label = "Descrição"
		return form 

	def form_valid(self, form):
		messages.info(self.request, f"Processo " +  " \""+ form.cleaned_data['process_name'] + f"\" inserido no sistema")
		return super(ProcessCreate, self).form_valid(form)

class ProcessUpdate(UpdateView):
	model = Process
	fields = ['process_name', 'description' , 'user']
	template_name = "processes/forms/process_update_form.html"
	def get_form(self, form_class=None):
		if form_class is None:
			form_class = self.get_form_class()
		form = super(ProcessUpdate, self).get_form(form_class)
		perm = Permission.objects.get(codename='test_GProc')  
		gp_users = User.objects.filter(groups__permissions=perm)
		form.fields['user'] = forms.ModelChoiceField(queryset=gp_users)
		form.fields['user'].empty_label = None
		form.fields['process_name'].label = "Nome do Processo"
		form.fields['description'].label = "Descrição"
		return form

	def form_valid(self, form):
		messages.info(self.request, f"Processo " +  " \""+ form.cleaned_data['process_name'] + f"\" alterado com sucesso")
		return super(ProcessUpdate, self).form_valid(form)

class ProcessDelete(DeleteView):
	model = Process
	sucess_url = "/processos"
	template_name = "processes/forms/process_confirm_delete.html"
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		proc_id = self.object.id
		our_acts = Activity.objects.all().filter(process__id=proc_id)
		context['acts'] = our_acts
		return context
	def delete(self, request, *args, **kwargs):

templates/processes/actividades.html
	
				{% extends "main/navbar.html" %}
				{% block content %}
				{% if perms.Users.test_GProc or perms.Users.test_Analist %}
				<div class="container">
						<div class="container-fluid" style=" margin-top:-25px;">
								<div class="row">
									<div class="navegation">
										<a href='{% url "home" %}'><i class="material-icons">home</i></a>
										<i class="material-icons" style="position:relative; top:5px;">keyboard_arrow_right</i>
										<b><span class="text-dark" id="path">Actividades</span></b>
									</div>
				<br><br>
				{% include "processes/includes/messages.html" %}
					<table class="table table-hover header-fixed">
						<thead>
							<tr class="d-flex">
								<th class="col-9">ACTIVIDADES BASE</th>
								<th class="col-3 text-right">
									<a class="dropdown-toggle" id="sidebarCollapse" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span>Mais recente</span><i class="material-icons">arrow_drop_down</i></a>
									<div class="dropdown-menu">
										<a class="dropdown-item" href="#">Mais antigo</a>
										<a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_downward</i></a>
										<a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_upward</i></a>
									</div>
								</th>
							</tr>
							<tr class="d-flex nobluebar">
									<td class="col-9"><b><a href="/actividades/ActivityCreate" class="novo"><i class="material-icons">add</i> Nova Actividade</a></b></td>
									<td class="col-3 text-right"></td>
								</tr>
								{% if acts|length > 0 %}
							<tr class="d-flex nobluebar">
								<td class="col-2"><b>Actividade:</b> </td>
								<td class="col-4"><b>Descrição: </b></td>
								
							</tr>
							{% endif %}
					</thead>
						<tbody class="proctable">
								{% for act in acts %}
								<tr class="d-flex">
								
										<td class="col-2"><a href="/actividades/ActivityDetail/{{act.id}}">{{act.activity_name}} </a></td>
										<td class="col-4">{{act.description}}</td>
										<td class="col-6 text-right">
										<a href="/actividades/ActivityUpdate/{{act.id}} "><i class="material-icons">create</i></a></b>
							
							
										<a href="/actividades/ActivityDelete/{{act.id}} "><i class="material-icons text-danger">clear</i></a>
									</td>
									</div>
									</tr>
									{% endfor %}
							
						</tbody>
					</table>
				
					<br>

					<table class="table table-hover header-fixed">
							<thead>
								<tr class="d-flex">
									<th class="col-9">ACTIVIDADES-PROCESSO</th>
									<th class="col-3 text-right">
										<a class="dropdown-toggle" id="sidebarCollapse" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span>Mais recente</span><i class="material-icons">arrow_drop_down</i></a>
										<div class="dropdown-menu">
											<a class="dropdown-item" href="#">Mais antigo</a>
											<a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_downward</i></a>
											<a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_upward</i></a>
										</div>
									</th>
								</tr>
									{% if proc_acts|length > 0 %}
								<tr class="d-flex nobluebar">
									<td class="col-2"><b>Actividade:</b> </td>
									<td class="col-4"><b>Processo: </b></td>
									
								</tr>
								{% endif %}
						</thead>
							<tbody class="proctable">
									{% for act in proc_acts %}
									<tr class="d-flex">
									
											<td class="col-2"><a href="/actividades/ActivityDetail/{{act.id}}">{{act.activity_name}} </a></td>
											<td class="col-4"><a href="/processos/ProcessDetail/{{act.process.id}}">{{act.process}}</a></td>
											<td class="col-6 text-right">
													{% if perms.Users.test_GProc %}
													<a href="/actividades/ActivityUpdate/{{act.id}} "><i class="material-icons">create</i></a></b>
								
											<a href="/actividades/ActivityDelete/{{act.id}} "><i class="material-icons text-danger">clear</i></a>
										{% endif %}
										</td>
										</div>
										</tr>
										{% endfor %}
								
							</tbody>
						</table>
            </div>
		</div>
	</div>
		

				{% else %}
				<h2>Não tem permissão para visualizar esta página.</h2>
				{% endif %}	
	{% endblock %}

templates/processes/empresas.html
{% extends "main/navbar.html" %}
{% block content %}
				{% if perms.Users.test_Admin %}
				{% include "processes/includes/admin_org_area.html" %}
			
			
				{% else %}
				<h2>Não tem permissão para visualizar esta página.</h2>
				{% endif %}	
{% endblock %}

templates/processes/homepage.html
{% extends "main/header.html" %}

{% block navbar %}

				
	
				{% include "main/navbar.html" %}
			
				
				
		
				{% if perms.Users.test_GProc or  perms.Users.test_Analist %}
				{% include "processes/includes/gp_main_area.html" %}
				{% elif perms.Users.test_Admin %}
				{% include "processes/includes/admin_main_area.html" %}
				{% endif %}
			
	
{% endblock %}

templates/processes/login.html
{% extends "processes/loginh.html" %}

{% block navbar %}
	<body>

		<div class="container text-center">
		<form class="form-signin" method="POST" action="{% url 'Users:login' %}">
			{% csrf_token %}
			{% for message in messages %}
			<div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
					<div class="toast-header">
					</div>
					<div class="toast-body">
							{% if message.tags == "error" %}<p class="alert alert-danger" role="alert">{{message}}<p>
							{% endif %}  
					</div>
				  </div>
		{% endfor %}
			<h2>LOGIN</h2><br>
			<input type="text" name="username" autofocus="" required="" id="id_username">
			<p class="nameErr text-danger text-left"></p>
		<input type="password" name="password" required="" id="id_password">
		<br><br>



						<div class="right">
							<button class="btn btn-lg btn-block text-white" type="submit">Login</button><!--bg-info-->
						</div>
		</form>
	</div>


{% endblock %}

templates/processes/loginh.html
<!DOCTYPE html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<!-- Our Custom CSS -->
  <link href="{% static 'css/login.css' %}" rel="stylesheet">
<!-- Font Awesome JS -->

</head>

<body>





    {% block navbar %}
    {% endblock %}


</body>

templates/processes/papeis.html
{% extends "main/navbar.html" %}
{% block content %}
				{% if perms.Users.test_GProc or  perms.Users.test_Analist %}
				<div class="container">
						<div class="container-fluid" style=" margin-top:-25px;">
								<div class="row">
									<div class="navegation">
										<a href='{% url "home" %}'><i class="material-icons">home</i></a>
										<i class="material-icons" style="position:relative; top:5px;">keyboard_arrow_right</i>
										<b><span class="text-dark" id="path">Papéis</span></b>
									</div>
				<br><br>
				{% include "processes/includes/messages.html" %}
					<table class="table table-hover header-fixed">
						<thead>
							<tr class="d-flex">
								<th class="col-9">PAPÉIS</th>
								<th class="col-3 text-right">
									<a class="dropdown-toggle" id="sidebarCollapse" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span>Mais recente</span><i class="material-icons">arrow_drop_down</i></a>
									<div class="dropdown-menu">
										<a class="dropdown-item" href="#">Mais antigo</a>
										<a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_downward</i></a>
										<a class="dropdown-item" href="#">Nome <i class="material-icons">arrow_upward</i></a>
									</div>
								</th>
							</tr>
							{% if perms.Users.test_GProc %}
									<tr class="d-flex nobluebar">
										<td class="col-9"><b><a href="/papeis/RoleCreate" class="novo"><i class="material-icons">add</i>Registar Papel</a></b></td>
										<td class="col-3 text-right"></td>
									</tr>
									{% endif %}
									{% if roles|length > 0 %}
							<tr class="d-flex nobluebar">
								<td class="col-3"><b>Papel:</b> </td>
								<td class="col-3"><b>Actividades:</b> </td>

							</tr>
							{% endif %}
						</thead>
						<tbody class="proctable"> 
								{% for role in roles %}
								<tr class="d-flex">
								
										<td class="col-3"><span><a href="/papeis/RoleDetail/{{role.id}}">{{role.role_name}} </a></span></td>
										<td class="col-3">
											{% for act in acts %}
											{% for rol in act.role.all %}
												{% if rol.id == role.id %}

													{{act.activity_name}}		<br>
													{% endif %}
											{% endfor %}	
											{% endfor %}</td>
										</span></td>
										{% if perms.Users.test_GProc %}
										<td class="col-6 text-right"><a href="/papeis/RoleUpdate/{{role.id}} "><i class="material-icons">create</i></a>
										<a href="/papeis/RoleDelete/{{role.id}} "><i class="material-icons text-danger">clear</i></a></td>
						{% endif %}
									</tr>
									{% endfor %}
							
						</tbody>
		
					</table>
				
            </div>
		</div>
		{% else %}
		<h2>Não tem permissão para visualizar esta página.</h2>
		{% endif %}	

		{% endblock %}

templates/processes/utilizadores.html
{% extends "main/navbar.html" %}
{% block content %}
				{% if perms.Users.test_Admin %}
				{% endif %}
				
			
				{% if perms.Users.test_Admin %}
				{% include "processes/includes/admin_user_area.html" %}
			
				{% else %}
				<h2>Não tem permissão para visualizar esta página.</h2>
				{% endif %}	
			
		
{% endblock %}